import { createDefaultBrowserForm, createDefaultBrowserState } from "./browserDefaults";
import { createDefaultLogForm, createDefaultLogState } from "./logDefaults";
import { createDefaultNetworkForm, createDefaultNetworkState } from "./networkDefaults";
import { createDefaultScheduleForm, createDefaultScheduleState, DEFAULT_CRON_TIMEZONE } from "./scheduleDefaults";
import { createDefaultSearchForm, createDefaultSearchState } from "./searchDefaults";

export function createSettingsForm(state) {
  return {
    wsUrl: state.wsUrl,
    accessToken: state.accessToken,
    displayName: state.displayName,
    externalChatId: state.activeExternalChatId,
    showWorkState: state.showWorkState,
    showRunHistory: state.showRunHistory,
    showRunTimeline: state.showRunTimeline,
    showRunSummary: state.showRunSummary,
    showRunTrace: state.showRunTrace,
    language: state.language,
    colorScheme: state.colorScheme,
  };
}

export function createSettingsState() {
  return {
    channelsLoading: false,
    channelsError: "",
    channelsNotice: "",
    channels: {
      connected: [],
      available: [],
      channels: [],
    },
    channelConnectForm: {
      type: "",
      name: "",
      token: "",
    },
    providersLoading: false,
    providersError: "",
    providersNotice: "",
    providers: {
      default_provider: null,
      connected: [],
      available: [],
    },
    credentials: {},
    codexAuthLoading: false,
    codexAuthError: "",
    codexAuthNotice: "",
    codexAuth: {
      configured: false,
      expired: false,
      expires_at: null,
      account_id: "",
      path: "",
      command: "",
      verificationUri: "",
      userCode: "",
      deviceAuthId: "",
      pollIntervalSeconds: 5,
    },
    copilotAuthLoading: false,
    copilotAuthError: "",
    copilotAuthNotice: "",
    copilotAuth: {
      configured: false,
      path: "",
      verificationUri: "",
      userCode: "",
      deviceCode: "",
      pollIntervalSeconds: 5,
    },
    connectForm: {
      providerId: "",
      name: "",
      apiKey: "",
      baseUrl: "",
      showAdvanced: false,
    },
    updateLoading: false,
    updateError: "",
    updateNotice: "",
    updateStatus: {
      supported: false,
      update_available: false,
      commits_behind: 0,
      dirty: false,
      branch: "",
      current_rev_short: "",
      project_root: "",
    },
    modelsLoading: false,
    modelsError: "",
    modelsNotice: "",
    models: {
      default_provider: null,
      active_model: "",
      providers: [],
    },
    selectedTextProviderId: "",
    modelSelections: {},
    reasoningSelections: {},
    customModels: {},
    mediaLoading: false,
    mediaError: "",
    mediaNotice: "",
    media: {
      sections: {
        vision: { category: "vision", enabled: false, provider_id: "", model: "" },
        ocr: { category: "ocr", enabled: false, provider_id: "", model: "" },
        speech: { category: "speech", enabled: false, provider_id: "", model: "" },
        video: { category: "video", enabled: false, provider_id: "", model: "" },
      },
      providers: [],
    },
    mediaSelections: {
      vision: { enabled: false, providerId: "", model: "" },
      ocr: { enabled: false, providerId: "", model: "" },
      speech: { enabled: false, providerId: "", model: "" },
      video: { enabled: false, providerId: "", model: "" },
    },
    mediaCustomModels: {},
    scheduleLoading: false,
    scheduleError: "",
    scheduleNotice: "",
    schedule: createDefaultScheduleState(),
    scheduleForm: createDefaultScheduleForm(),
    networkLoading: false,
    networkError: "",
    networkNotice: "",
    network: createDefaultNetworkState(),
    networkForm: createDefaultNetworkForm(),
    searchLoading: false,
    searchOptionsLoading: false,
    searchError: "",
    searchOptionsError: "",
    searchNotice: "",
    searchOptionsNotice: "",
    search: createDefaultSearchState(),
    searchForm: createDefaultSearchForm(),
    browserLoading: false,
    browserTestLoading: false,
    browserDoctorLoading: false,
    browserInstallLoading: false,
    browserError: "",
    browserNotice: "",
    browserTestResult: null,
    browserDoctorResult: null,
    browserInstallResult: null,
    browser: createDefaultBrowserState(),
    browserForm: createDefaultBrowserForm(),
    logLoading: false,
    logError: "",
    logNotice: "",
    log: createDefaultLogState(),
    logForm: createDefaultLogForm(),
    cronJobsLoading: false,
    cronJobsError: "",
    cronJobsNotice: "",
    cronJobs: [],
    cronJobForm: {
      showEditor: false,
      sessionId: "",
      jobId: "",
      mode: "cron",
      name: "",
      message: "",
      everySeconds: "3600",
      cronExpr: "0 9 * * *",
      at: "",
      timezone: DEFAULT_CRON_TIMEZONE,
      deliver: true,
    },
    mcpLoading: false,
    mcpError: "",
    mcpNotice: "",
    mcpToolGroupsExpanded: {},
    mcp: {
      servers: [],
      runtime: {
        connected: false,
        connecting: false,
        connect_failures: 0,
        tool_names: [],
      },
    },
    mcpForm: {
      showEditor: false,
      editingId: "",
      serverId: "",
      type: "stdio",
      command: "",
      argsText: "",
      url: "",
      envJson: "",
      headersJson: "",
      toolTimeout: "30",
      enabledToolsText: "*",
      showAdvanced: false,
      showJsonInput: false,
      jsonText: "",
    },
  };
}
