import { createDefaultBrowserForm, createDefaultBrowserState } from "./browserDefaults";
import { createDefaultLogForm, createDefaultLogState } from "./logDefaults";
import { createDefaultNetworkForm, createDefaultNetworkState } from "./networkDefaults";
import { createDefaultPermissionsForm, createDefaultPermissionsState } from "./permissionsDefaults";
import { createDefaultScheduleForm, createDefaultScheduleState, DEFAULT_CRON_TIMEZONE } from "./scheduleDefaults";
import { createDefaultSearchForm, createDefaultSearchState } from "./searchDefaults";

export function createSettingsForm(state) {
  return {
    wsUrl: state.wsUrl,
    accessToken: state.accessToken,
    displayName: state.displayName,
    externalChatId: state.activeExternalChatId,
    showWorkState: state.showWorkState,
    showRunHistory: state.showRunHistory,
    showRunTimeline: state.showRunTimeline,
    showRunSummary: state.showRunSummary,
    showRunTrace: state.showRunTrace,
    language: state.language,
    colorScheme: state.colorScheme,
  };
}

export function createSettingsState() {
  return {
    channelsLoading: false,
    channelsError: "",
    channelsNotice: "",
    channels: {
      connected: [],
      available: [],
      channels: [],
    },
    channelConnectForm: {
      type: "",
      name: "",
      token: "",
    },
    providersLoading: false,
    providersError: "",
    providersNotice: "",
    providers: {
      default_provider: null,
      connected: [],
      available: [],
    },
    credentials: {},
    codexAuthLoading: false,
    codexAuthError: "",
    codexAuthNotice: "",
    codexAuth: {
      configured: false,
      expired: false,
      expires_at: null,
      account_id: "",
      path: "",
      command: "",
      verificationUri: "",
      userCode: "",
      deviceAuthId: "",
      pollIntervalSeconds: 5,
    },
    copilotAuthLoading: false,
    copilotAuthError: "",
    copilotAuthNotice: "",
    copilotAuth: {
      configured: false,
      path: "",
      verificationUri: "",
      userCode: "",
      deviceCode: "",
      pollIntervalSeconds: 5,
    },
    connectForm: {
      providerId: "",
      name: "",
      apiKey: "",
      baseUrl: "",
      showAdvanced: false,
    },
    updateLoading: false,
    updateError: "",
    updateNotice: "",
    updateStatus: {
      supported: false,
      update_available: false,
      commits_behind: 0,
      dirty: false,
      branch: "",
      current_rev_short: "",
      project_root: "",
    },
    modelsLoading: false,
    modelsError: "",
    modelsNotice: "",
    llmLoading: false,
    llmError: "",
    llmNotice: "",
    llm: {
      effective_request: null,
    },
    models: {
      default_provider: null,
      active_model: "",
      providers: [],
    },
    selectedTextProviderId: "",
    modelSelections: {},
    customModels: {},
    providerRequestOptions: {},
    mediaLoading: false,
    mediaError: "",
    mediaNotice: "",
    media: {
      sections: {
        vision: { category: "vision", enabled: false, provider_id: "", model: "" },
        ocr: { category: "ocr", enabled: false, provider_id: "", model: "" },
        speech: { category: "speech", enabled: false, provider_id: "", model: "" },
        video: { category: "video", enabled: false, provider_id: "", model: "" },
      },
      providers: [],
    },
    mediaSelections: {
      vision: { enabled: false, providerId: "", model: "" },
      ocr: { enabled: false, providerId: "", model: "" },
      speech: { enabled: false, providerId: "", model: "" },
      video: { enabled: false, providerId: "", model: "" },
    },
    mediaCustomModels: {},
    scheduleLoading: false,
    scheduleError: "",
    scheduleNotice: "",
    schedule: createDefaultScheduleState(),
    scheduleForm: createDefaultScheduleForm(),
    networkLoading: false,
    networkError: "",
    networkNotice: "",
    network: createDefaultNetworkState(),
    networkForm: createDefaultNetworkForm(),
    permissionsLoading: false,
    permissionsError: "",
    permissionsNotice: "",
    permissions: createDefaultPermissionsState(),
    permissionsForm: createDefaultPermissionsForm(),
    harnessPolicyPreviewLoading: false,
    harnessPolicyPreviewError: "",
    harnessPolicyPreview: { rows: [], user_permissions: null },
    searchLoading: false,
    searchOptionsLoading: false,
    searchError: "",
    searchOptionsError: "",
    searchNotice: "",
    searchOptionsNotice: "",
    search: createDefaultSearchState(),
    searchForm: createDefaultSearchForm(),
    browserLoading: false,
    browserTestLoading: false,
    browserDoctorLoading: false,
    browserInstallLoading: false,
    browserError: "",
    browserNotice: "",
    browserTestResult: null,
    browserDoctorResult: null,
    browserInstallResult: null,
    browser: createDefaultBrowserState(),
    browserForm: createDefaultBrowserForm(),
    logLoading: false,
    logError: "",
    logNotice: "",
    log: createDefaultLogState(),
    logForm: createDefaultLogForm(),
    dataLoading: false,
    dataError: "",
    dataStatus: {
      storage: {
        type: "",
        path: "",
        provider: "",
      },
      counts: {
        sessions: 0,
        raw_sessions: 0,
        messages: 0,
        runs: 0,
      },
    },
    dataSessions: [],
    dataSelectedSessionId: "",
    dataTimelineLoading: false,
    dataTimelineError: "",
    dataTimeline: {
      session_id: "",
      messages: [],
      runs: [],
      entries: [],
    },
    evalLoading: false,
    evalRunning: false,
    evalError: "",
    evalNotice: "",
    evalStatus: {
      ready: false,
      storage_available: false,
      background_process_counts: {},
      recent_background_processes: 0,
      recommended_metrics: [],
      recommended_scenarios: [],
    },
    evalSmoke: {
      ok: false,
      checks: [],
      background_process_counts: {},
      metrics: [],
    },
    harnessEvalRunning: false,
    harnessEval: {
      ok: false,
      cases: [],
      summary: {
        passed_cases: 0,
        total_cases: 0,
        passed_checks: 0,
        total_checks: 0,
      },
    },
    taskCompletionRunning: false,
    taskCompletionSmoke: {
      ok: false,
      cases: [],
      summary: {
        passed_cases: 0,
        total_cases: 0,
        passed_checks: 0,
        total_checks: 0,
      },
    },
    taskCompletionLiveRunning: false,
    taskCompletionLive: {
      ok: false,
      cases: [],
      summary: {
        passed_cases: 0,
        total_cases: 0,
        passed_checks: 0,
        total_checks: 0,
      },
    },
    taskCompletionHistoryLoading: false,
    taskCompletionHistoryError: "",
    taskCompletionHistory: [],
    cronJobsLoading: false,
    cronJobsError: "",
    cronJobsNotice: "",
    cronJobs: [],
    cronJobForm: {
      showEditor: false,
      sessionId: "",
      jobId: "",
      mode: "cron",
      name: "",
      message: "",
      everySeconds: "3600",
      cronExpr: "0 9 * * *",
      at: "",
      timezone: DEFAULT_CRON_TIMEZONE,
      deliver: true,
    },
    mcpLoading: false,
    mcpError: "",
    mcpNotice: "",
    mcpToolGroupsExpanded: {},
    mcp: {
      servers: [],
      runtime: {
        connected: false,
        connecting: false,
        connect_failures: 0,
        tool_names: [],
      },
    },
    mcpForm: {
      showEditor: false,
      editingId: "",
      serverId: "",
      type: "stdio",
      command: "",
      argsText: "",
      url: "",
      envJson: "",
      headersJson: "",
      toolTimeout: "30",
      enabledToolsText: "*",
      showAdvanced: false,
      showJsonInput: false,
      jsonText: "",
    },
  };
}

export function createPermissionState() {
  return {
    loading: false,
    error: "",
    requests: [],
    resolvingIds: {},
  };
}

export function createCuratorState() {
  return {
    loading: false,
    action: "",
    error: "",
    status: null,
    history: [],
    historyLoading: false,
    historyError: "",
  };
}
