export function createSettingsForm(state) {
  return {
    wsUrl: state.wsUrl,
    displayName: state.displayName,
    externalChatId: state.activeExternalChatId,
    showRunTimeline: state.showRunTimeline,
    showRunSummary: state.showRunSummary,
    showRunTrace: state.showRunTrace,
    language: state.language,
    colorScheme: state.colorScheme,
  };
}

export function createSettingsState() {
  return {
    channelsLoading: false,
    channelsError: "",
    channelsNotice: "",
    channels: {
      connected: [],
      available: [],
      channels: [],
    },
    channelConnectForm: {
      type: "",
      name: "",
      token: "",
    },
    providersLoading: false,
    providersError: "",
    providersNotice: "",
    providers: {
      default_provider: null,
      connected: [],
      available: [],
    },
    credentials: {},
    codexAuthLoading: false,
    codexAuthError: "",
    codexAuthNotice: "",
    codexAuth: {
      configured: false,
      expired: false,
      expires_at: null,
      account_id: "",
      path: "",
      command: "",
      verificationUri: "",
      userCode: "",
      deviceAuthId: "",
      pollIntervalSeconds: 5,
    },
    copilotAuthLoading: false,
    copilotAuthError: "",
    copilotAuthNotice: "",
    copilotAuth: {
      configured: false,
      path: "",
      verificationUri: "",
      userCode: "",
      deviceCode: "",
      pollIntervalSeconds: 5,
    },
    connectForm: {
      providerId: "",
      name: "",
      apiKey: "",
      baseUrl: "",
      showAdvanced: false,
    },
    updateLoading: false,
    updateError: "",
    updateNotice: "",
    updateStatus: {
      supported: false,
      update_available: false,
      commits_behind: 0,
      dirty: false,
      branch: "",
      current_rev_short: "",
      project_root: "",
    },
    modelsLoading: false,
    modelsError: "",
    modelsNotice: "",
    llmLoading: false,
    llmError: "",
    llmNotice: "",
    llm: {
      pass_decoding_params: true,
    },
    models: {
      default_provider: null,
      active_model: "",
      providers: [],
    },
    selectedTextProviderId: "",
    modelSelections: {},
    customModels: {},
    openRouterOptions: {},
    mediaLoading: false,
    mediaError: "",
    mediaNotice: "",
    media: {
      sections: {
        vision: { category: "vision", enabled: false, provider_id: "", model: "" },
        ocr: { category: "ocr", enabled: false, provider_id: "", model: "" },
        speech: { category: "speech", enabled: false, provider_id: "", model: "" },
        video: { category: "video", enabled: false, provider_id: "", model: "" },
      },
      providers: [],
    },
    mediaSelections: {
      vision: { enabled: false, providerId: "", model: "" },
      ocr: { enabled: false, providerId: "", model: "" },
      speech: { enabled: false, providerId: "", model: "" },
      video: { enabled: false, providerId: "", model: "" },
    },
    mediaCustomModels: {},
    scheduleLoading: false,
    scheduleError: "",
    scheduleNotice: "",
    schedule: {
      default_timezone: "UTC",
      common_timezones: [],
    },
    scheduleForm: {
      defaultTimezone: "UTC",
    },
    networkLoading: false,
    networkError: "",
    networkNotice: "",
    network: {
      http_proxy: "",
      https_proxy: "",
      no_proxy: "127.0.0.1,localhost",
    },
    networkForm: {
      httpProxy: "",
      httpsProxy: "",
      noProxy: "127.0.0.1,localhost",
    },
    cronJobsLoading: false,
    cronJobsError: "",
    cronJobsNotice: "",
    cronJobs: [],
    cronJobForm: {
      showEditor: false,
      sessionId: "",
      jobId: "",
      mode: "cron",
      name: "",
      message: "",
      everySeconds: "3600",
      cronExpr: "0 9 * * *",
      at: "",
      timezone: "UTC",
      deliver: true,
    },
    mcpLoading: false,
    mcpError: "",
    mcpNotice: "",
    mcpToolGroupsExpanded: {},
    mcp: {
      servers: [],
      runtime: {
        connected: false,
        connecting: false,
        connect_failures: 0,
        tool_names: [],
      },
    },
    mcpForm: {
      showEditor: false,
      editingId: "",
      serverId: "",
      type: "stdio",
      command: "",
      argsText: "",
      url: "",
      envJson: "",
      headersJson: "",
      toolTimeout: "30",
      enabledToolsText: "*",
      showAdvanced: false,
      showJsonInput: false,
      jsonText: "",
    },
  };
}

export function createPermissionState() {
  return {
    loading: false,
    error: "",
    requests: [],
    resolvingIds: {},
  };
}

export function createCuratorState() {
  return {
    loading: false,
    action: "",
    error: "",
    status: null,
    history: [],
    historyLoading: false,
    historyError: "",
  };
}
