"""Compatibility exports for tool access, harness policy, and loop guardrails."""

from __future__ import annotations

from ..config import AgentConfig, ToolsConfig
from ..context.message_history import HISTORY_SEARCH_TOOL_NAME
from ..permission_constants import (
    ALL_RISK_LEVELS,
    ALL_RISK_LEVELS_ORDER,
    APPROVAL_MODE_ASK,
    APPROVAL_MODE_AUTO,
    RISK_LEVEL_DELEGATION,
    RISK_LEVEL_EXTERNAL_SIDE_EFFECT,
    RISK_LEVEL_MCP,
    RISK_LEVEL_NETWORK,
    RISK_LEVEL_READ,
    denied_risks_except,
)
from ..tool_names import (
    ANALYZE_IMAGE_TOOL_NAME,
    ANALYZE_VIDEO_TOOL_NAME,
    APPLY_PATCH_TOOL_NAME,
    BATCH_TOOL_NAME,
    CONFIGURE_MCP_TOOL_NAME,
    CONFIGURE_SKILL_TOOL_NAME,
    CONFIGURE_SUBAGENT_TOOL_NAME,
    CREDENTIAL_STORE_TOOL_NAME,
    CRON_TOOL_NAME,
    DELEGATED_EXECUTION_TOOL_NAMES,
    DELEGATE_TOOL_NAME,
    EXEC_TOOL_NAME,
    EXECUTION_TOOL_NAMES,
    LIST_RUN_FILE_CHANGES_TOOL_NAME,
    MEDIA_ANALYSIS_TOOL_NAMES,
    MEDIA_TOOL_NAMES,
    OCR_IMAGE_TOOL_NAME,
    PREVIEW_RUN_FILE_CHANGE_REVERT_TOOL_NAME,
    READ_FILE_TOOL_NAME,
    READ_SKILL_TOOL_NAME,
    SEND_MEDIA_TOOL_NAME,
    TASK_UPDATE_TOOL_NAME,
    TRANSCRIBE_AUDIO_TOOL_NAME,
    WEB_SEARCH_TOOL_NAME,
    WORKSPACE_DISCOVERY_TOOL_NAMES,
    WORKSPACE_WRITE_TOOL_NAMES,
)
from ..tools.approval import DEFAULT_PERMISSION_DENIAL_REASON, PermissionRequest, PermissionRequestManager
from ..tools.evidence import (
    VERIFICATION_TOOL_NAME,
    WEB_HARNESS_RESEARCH_TOOLS,
    WEB_RESEARCH_TASK_TYPE,
    WEB_RESEARCH_TOOL_GROUP,
    WEB_SOURCE_ARTIFACT_TOOLS,
    WEB_SOURCE_EVIDENCE_TOOLS,
    WEB_SOURCE_REQUIRED_EVIDENCE,
)
from ..tools.loop_guardrail import (
    IDEMPOTENT_TOOL_NAMES,
    MUTATING_TOOL_NAMES,
    ToolCallSignature,
    ToolLoopGuardrail,
    ToolLoopGuardrailConfig,
    ToolLoopGuardrailDecision,
    append_toolguard_guidance,
    build_toolguard_synthetic_result,
)
from ..tools.memory import SaveMemoryTool
from ..tools.permissions import (
    PermissionApprovalResult,
    PermissionDecision,
    ToolPermissionPolicy,
)
from ..tools.registry import ToolRegistry
from ..tools.access import (
    EffectivePolicyResolution,
    ToolAccessResolution,
    ToolAccessResolver,
    planning_mode_permission_policy,
    summarize_effective_risks,
)
from ..tools.approval_runtime import AgentPermissionService, PermissionEventRecorder
from ..tools.registration import (
    BROWSER_TOOL_NAMES,
    register_batch_tools,
    register_browser_tools,
    register_config_tools,
    register_cron_tools,
    register_default_tools,
    register_delegate_tools,
    register_filesystem_tools,
    register_media_tools,
    register_memory_tool,
    register_run_trace_tools,
    register_search_tools,
    register_shell_tools,
    register_skill_tools,
    register_task_tools,
    register_verify_tools,
    register_web_tools,
    register_workflow_tools,
)

from ..harness import (
    ANALYSIS_TASK_TYPE,
    CHAT_HARNESS_POLICY_REASON,
    CHAT_PROFILE_NAME,
    CODE_CHANGE_TASK_TYPE,
    CODING_PROFILE_NAME,
    CONTRACT_MEDIA_PROFILE_REASON,
    CONTRACT_OPERATIONS_PROFILE_REASON,
    CONTRACT_PLANNING_PROFILE_REASON,
    CONTRACT_PURE_ANSWER_PROFILE_REASON,
    CONTRACT_WEB_RESEARCH_PROFILE_REASON,
    CONTRACT_WORKSPACE_CHANGE_PROFILE_REASON,
    CONTRACT_WORKSPACE_EVIDENCE_PROFILE_REASON,
    DEFAULT_CHAT_PROFILE_REASON,
    EXECUTION_TOOL_GROUP,
    FILE_CHANGE_REQUIREMENT_KIND,
    GENERIC_TASK_TYPE,
    HARNESS_APPROVAL_REQUIREMENT_PROTECTED_REASON,
    HARNESS_SENSOR_FAIL_STATUS,
    HARNESS_SENSOR_NOT_APPLICABLE_STATUS,
    HARNESS_SENSOR_PASS_STATUS,
    HARNESS_SENSOR_WARN_STATUS,
    HISTORY_RETRIEVAL_TASK_TYPE,
    HISTORY_RETRIEVAL_TOOL_GROUP,
    MEDIA_EXTRACTION_TASK_TYPE,
    MEDIA_HARNESS_POLICY_REASON,
    MEDIA_PROFILE_NAME,
    MEDIA_TOOL_GROUP,
    OPERATIONS_HARNESS_POLICY_REASON,
    OPERATIONS_TASK_TYPE,
    OPERATION_TOOL_GROUPS,
    PLANNING_TASK_TYPE,
    POLICY_RESOLUTION_METADATA_REASON,
    PREVIEW_CHAT_PROFILE_REASON,
    PREVIEW_MEDIA_PROFILE_REASON,
    PREVIEW_OPERATIONS_PROFILE_REASON,
    PREVIEW_WEB_RESEARCH_PROFILE_REASON,
    PREVIEW_WORKSPACE_ANALYSIS_PROFILE_REASON,
    PREVIEW_WORKSPACE_CHANGE_PROFILE_REASON,
    PURE_ANSWER_TASK_TYPE,
    RESEARCH_HARNESS_POLICY_REASON,
    RESEARCH_PROFILE_NAME,
    SCHEDULING_TOOL_GROUP,
    SENSOR_CHAT_NO_UNEXPECTED_TOOLS,
    SENSOR_CODING_FILE_CHANGE,
    SENSOR_CODING_VERIFICATION,
    SENSOR_CODING_WORKSPACE_EVIDENCE,
    SENSOR_COMPLETION_CHANGE_SUMMARY,
    SENSOR_COMPLETION_FINAL_ANSWER,
    SENSOR_COMPLETION_MEDIA_SUMMARY,
    SENSOR_COMPLETION_OPERATION_REPORT,
    SENSOR_COMPLETION_SOURCE_GROUNDING,
    SENSOR_COMPLETION_VERIFICATION_OR_GAP,
    SENSOR_IDS_BY_TASK_TYPE,
    SENSOR_MEDIA_ARTIFACT,
    SENSOR_OPS_APPROVAL_BOUNDARY,
    SENSOR_OPS_AUDIT_TRACE,
    SENSOR_RESEARCH_FRESHNESS,
    SENSOR_RESEARCH_SOURCE_COVERAGE,
    TASK_TYPE_BY_TOOL_GROUP,
    TOOL_GROUPS,
    TOOL_GROUP_BY_TOOL_NAME,
    VERIFICATION_REQUIREMENT_KIND,
    VERIFICATION_TOOL_GROUP,
    WORKSPACE_ANALYSIS_HARNESS_POLICY_REASON,
    WORKSPACE_ANALYSIS_TASK_TYPE,
    WORKSPACE_CHANGE_TASK_TYPE,
    WORKSPACE_DISCOVERY_TOOLS,
    WORKSPACE_READ_TASK_TYPE,
    WORKSPACE_READ_TOOL_GROUP,
    WORKSPACE_WRITE_TOOL_GROUP,
    HarnessCheckStatus,
    HarnessInventoryItem,
    HarnessPolicy,
    HarnessPolicyService,
    HarnessProfile,
    HarnessProfileService,
    HarnessScorecard,
    HarnessSensorResult,
    build_harness_inventory,
    evaluate_harness_sensors,
    expected_sensor_ids_for_task_type,
    harness_inventory_payload,
    harness_profile_follow_up_instruction,
    is_chat_profile_name,
    is_coding_profile_name,
    is_media_profile_name,
    is_ops_profile_name,
    is_planning_task_type,
    is_research_profile_name,
    normalize_profile_name,
    preview_harness_profiles,
)
