<template>
  <div class="app-shell" :class="{ 'app-shell--sidebar-collapsed': sidebarCollapsed }">
    <button
      class="mobile-nav-toggle"
      type="button"
      aria-controls="sidebar"
      :aria-expanded="String(sidebarOpen)"
      @click="toggleSidebar"
    >
      {{ copy.app.menu }}
    </button>

    <SidebarNav
      :copy="copy"
      :state="state"
      :sessions="sidebarSessions"
      :session-channel-filter="sessionChannelFilter"
      :collapsed="sidebarCollapsed"
      :get-session-display-id="getSessionDisplayId"
      :get-session-title="getSessionTitle"
      @create-new-chat="createNewChat"
      @set-active-session="setActiveSession"
      @set-session-channel-filter="setSessionChannelFilter"
      @toggle-sidebar-collapsed="toggleSidebarCollapsed"
      @open-settings="openSettings()"
    />

    <ChatPanel
      :copy="copy"
      :prompts="prompts"
      :entries="currentEntries"
      :messages="currentMessages"
      :work-state="currentWorkState"
      :runs="currentRuns"
      :runs-loading="currentRunsLoading"
      :runs-error="currentRunsError"
      :current-run="currentRun"
      :run-timeline="currentRunTimeline"
      :run-summary="currentRunSummary"
      :permission-state="permissionState"
      :permission-requests="currentPermissionRequests"
      :show-run-timeline="state.showRunTimeline"
      :show-run-summary="state.showRunSummary"
      :show-run-trace="state.showRunTrace"
      :notice="state.notice"
      :session-meta="sessionMeta"
      :runtime-hint="composerHint"
      :display-name="state.displayName"
      :message-text="messageText"
      :connection-label="connectionLabel"
      :connect-button-label="connectButtonLabel"
      :status-dot-class="statusDotClass"
      :composer-read-only="currentSessionReadOnly"
      :send-disabled="sendDisabled"
      :connecting="state.connectionState === 'connecting'"
      :set-message-input-ref="setMessageInputRef"
      :set-message-stage-ref="setMessageStageRef"
      @connect="connectSocket"
      @apply-prompt="applyPrompt"
      @update-message-text="setMessageText"
      @composer-input="resizeComposer"
      @composer-keydown="handleComposerKeydown"
      @submit-message="submitMessage"
      @cancel-run="cancelRun"
      @resolve-permission="resolvePermissionRequest"
      @revert-file-change="revertRunFileChange"
      @cleanup-worktree="cleanupWorktreeSandbox"
      @select-run="selectRun"
    />
  </div>

  <SettingsModal
    :copy="copy"
    :open="settingsOpen"
    :section="settingsSection"
    :title="settingsTitle"
    :form="settingsForm"
    :settings-state="settingsState"
    :connection-state="state.connectionState"
    @close="closeSettings"
    @select-section="selectSettingsSection"
    @save-connection-settings="saveConnectionSettings"
    @toggle-connection="toggleSettingsConnection"
    @begin-channel-connect="beginChannelConnect"
    @cancel-channel-connect="cancelChannelConnect"
    @save-channel-connection="saveChannelConnection"
    @disconnect-channel="disconnectChannel"
    @begin-provider-connect="beginProviderConnect"
    @cancel-provider-connect="cancelProviderConnect"
    @save-provider-connection="saveProviderConnection"
    @disconnect-provider="disconnectProvider"
    @select-model="selectModel"
    @begin-mcp-create="beginMcpCreate"
    @save-mcp-server="saveMcpServer"
    @edit-mcp-server="beginMcpEdit"
    @cancel-mcp-edit="cancelMcpEdit"
    @remove-mcp-server="removeMcpServer"
    @reload-mcp-settings="reloadMcpSettings"
    @toggle-mcp-advanced="toggleMcpAdvanced"
    @toggle-mcp-json="toggleMcpJsonInput"
    @toggle-mcp-tool-group="toggleMcpToolGroup"
    @apply-mcp-json="applyMcpJson"
    @save-schedule-settings="saveScheduleSettings"
    @begin-cron-job-create="beginCronJobCreate"
    @save-cron-job="saveCronJob"
    @edit-cron-job="beginCronJobEdit"
    @cancel-cron-job-edit="cancelCronJobEdit"
    @cron-job-action="runCronJobAction"
  />
</template>

<script setup>
import ChatPanel from "./components/ChatPanel.vue";
import SettingsModal from "./components/SettingsModal.vue";
import SidebarNav from "./components/SidebarNav.vue";
import { useChatClient } from "./composables/useChatClient";

const {
  copy,
  prompts,
  state,
  sidebarSessions,
  sessionChannelFilter,
  messageText,
  sidebarOpen,
  sidebarCollapsed,
  settingsOpen,
  settingsSection,
  settingsForm,
  settingsState,
  permissionState,
  currentEntries,
  currentMessages,
  currentWorkState,
  currentRuns,
  currentRunsLoading,
  currentRunsError,
  currentRun,
  currentRunTimeline,
  currentRunSummary,
  currentPermissionRequests,
  settingsTitle,
  sessionMeta,
  composerHint,
  connectionLabel,
  connectButtonLabel,
  statusDotClass,
  currentSessionReadOnly,
  sendDisabled,
  setMessageInputRef,
  setMessageStageRef,
  setMessageText,
  getSessionDisplayId,
  getSessionTitle,
  setActiveSession,
  setSessionChannelFilter,
  selectRun,
  selectSettingsSection,
  openSettings,
  closeSettings,
  saveConnectionSettings,
  beginChannelConnect,
  cancelChannelConnect,
  saveChannelConnection,
  disconnectChannel,
  beginProviderConnect,
  cancelProviderConnect,
  saveProviderConnection,
  disconnectProvider,
  selectModel,
  beginMcpCreate,
  beginMcpEdit,
  cancelMcpEdit,
  saveMcpServer,
  removeMcpServer,
  reloadMcpSettings,
  toggleMcpAdvanced,
  toggleMcpJsonInput,
  toggleMcpToolGroup,
  applyMcpJson,
  saveScheduleSettings,
  beginCronJobCreate,
  beginCronJobEdit,
  cancelCronJobEdit,
  saveCronJob,
  runCronJobAction,
  toggleSidebar,
  toggleSidebarCollapsed,
  connectSocket,
  resizeComposer,
  createNewChat,
  cancelRun,
  resolvePermissionRequest,
  revertRunFileChange,
  cleanupWorktreeSandbox,
  toggleSettingsConnection,
  submitMessage,
  handleComposerKeydown,
  applyPrompt,
} = useChatClient();
</script>
