export const providerIds = ["openai", "anthropic"] as const;
export type ProviderId = (typeof providerIds)[number];
export type ProviderStatus = "disconnected" | "connected" | "invalid_credentials" | "provider_unreachable" | "provider_timeout" | "provider_rate_limited" | "credential_store_unavailable";
export type ServerErrorCode = "invalid_request" | "unsupported_provider" | "not_connected" | "invalid_credentials" | "provider_unreachable" | "provider_timeout" | "provider_rate_limited" | "credential_store_unavailable" | "internal_error";
export type ProviderErrorCode = ServerErrorCode | "malformed_response" | "network_error";
export type ProviderSummary = { id: ProviderId; name: "OpenAI" | "Anthropic"; connected: boolean; status: ProviderStatus; credentialPreview: string | null; lastCheckedAt: string | null };
const statuses: readonly ProviderStatus[] = ["disconnected", "connected", "invalid_credentials", "provider_unreachable", "provider_timeout", "provider_rate_limited", "credential_store_unavailable"];
const serverCodes: readonly ServerErrorCode[] = ["invalid_request", "unsupported_provider", "not_connected", "invalid_credentials", "provider_unreachable", "provider_timeout", "provider_rate_limited", "credential_store_unavailable", "internal_error"];
const allow = { list: new Map([[503,["credential_store_unavailable"]],[500,["internal_error"]]]), put: new Map([[400,["invalid_request"]],[404,["unsupported_provider"]],[422,["invalid_credentials"]],[429,["provider_rate_limited"]],[502,["provider_unreachable"]],[503,["credential_store_unavailable"]],[504,["provider_timeout"]],[500,["internal_error"]]]), test: new Map([[400,["invalid_request"]],[404,["unsupported_provider"]],[409,["not_connected"]],[422,["invalid_credentials"]],[429,["provider_rate_limited"]],[502,["provider_unreachable"]],[503,["credential_store_unavailable"]],[504,["provider_timeout"]],[500,["internal_error"]]]), delete: new Map([[404,["unsupported_provider"]],[503,["credential_store_unavailable"]],[500,["internal_error"]]]) } as const;
export class ProviderApiError extends Error { constructor(readonly code: ProviderErrorCode) { super(code); this.name = "ProviderApiError"; } }
const record = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v);
const keys = (v: Record<string, unknown>, expected: readonly string[]) => Object.keys(v).length === expected.length && Object.keys(v).every((key) => expected.includes(key));
function utc(v: unknown): v is string { const m = typeof v === "string" && /^(\d{4})-(\d{2})-(\d{2})T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)(?:\.\d+)?Z$/.exec(v); if (!m) return false; const [y,mo,d,h,mi,s] = m.slice(1,7).map(Number); const date = new Date(Date.UTC(y,mo-1,d,h,mi,s)); return date.getUTCFullYear()===y && date.getUTCMonth()===mo-1 && date.getUTCDate()===d && date.getUTCHours()===h && date.getUTCMinutes()===mi && date.getUTCSeconds()===s; }
function summary(v: unknown, expectedId?: ProviderId): ProviderSummary {
  if (!record(v) || !keys(v, ["id", "name", "connected", "status", "credentialPreview", "lastCheckedAt"])) throw new ProviderApiError("malformed_response");
  const { id, name, connected, status, credentialPreview, lastCheckedAt } = v;
  if (!providerIds.includes(id as ProviderId) || (id === "openai" && name !== "OpenAI") || (id === "anthropic" && name !== "Anthropic") || typeof connected !== "boolean" || !statuses.includes(status as ProviderStatus) || (credentialPreview !== null && typeof credentialPreview !== "string") || (lastCheckedAt !== null && !utc(lastCheckedAt)) || (expectedId && id !== expectedId)) throw new ProviderApiError("malformed_response");
  if (!connected && (status !== "disconnected" || credentialPreview !== null || lastCheckedAt !== null)) throw new ProviderApiError("malformed_response");
  if (connected && (status === "disconnected" || lastCheckedAt === null)) throw new ProviderApiError("malformed_response");
  return { id, name, connected, status, credentialPreview, lastCheckedAt } as ProviderSummary;
}
function envelope(v: unknown, codes: readonly string[]): ServerErrorCode { if (!record(v)||!keys(v,["error"])||!record(v.error)||!keys(v.error,["code","message","retryable"])||typeof v.error.code!=="string"||!serverCodes.includes(v.error.code as ServerErrorCode)||!codes.includes(v.error.code)||typeof v.error.message!=="string"||typeof v.error.retryable!=="boolean") throw new ProviderApiError("malformed_response"); return v.error.code as ServerErrorCode; }
async function call(path:string, init:RequestInit|undefined, errors:ReadonlyMap<number,readonly string[]>) { let response:Response; try { response=await fetch(path,init); } catch { throw new ProviderApiError("network_error"); } if (response.status !== 200) { if (response.ok) throw new ProviderApiError("malformed_response"); let errorBody:unknown; try { errorBody=await response.json(); } catch { throw new ProviderApiError("malformed_response"); } throw new ProviderApiError(envelope(errorBody, errors.get(response.status)??[])); } let body:unknown; try { body=await response.json(); } catch { throw new ProviderApiError("malformed_response"); } return body; }
export async function listProviderConnections() { const body=await call("/api/providers",undefined,allow.list); if (!record(body)||!keys(body,["providers"])||!Array.isArray(body.providers)||body.providers.length!==2) throw new ProviderApiError("malformed_response"); return body.providers.map((item,index)=>summary(item,providerIds[index])); }
export async function replaceProviderConnection(id:ProviderId,key:string) { const result=summary(await call(`/api/providers/${id}/connection`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey:key})},allow.put),id); if(!result.connected||result.status!=="connected") throw new ProviderApiError("malformed_response"); return result; }
export async function testProviderConnection(id:ProviderId) { const result=summary(await call(`/api/providers/${id}/connection/test`,{method:"POST"},allow.test),id); if(!result.connected||result.status!=="connected") throw new ProviderApiError("malformed_response"); return result; }
export async function deleteProviderConnection(id:ProviderId) { let response:Response;try{response=await fetch(`/api/providers/${id}/connection`,{method:"DELETE"});}catch{throw new ProviderApiError("network_error");}if(response.status===204)return;let body:unknown;try{body=await response.json();}catch{throw new ProviderApiError("malformed_response");}throw new ProviderApiError(response.ok?"malformed_response":envelope(body,allow.delete.get(response.status)??[])); }
export function providerErrorText(error:unknown) { const code=error instanceof ProviderApiError?error.code:"network_error"; return ({invalid_request:"送出的連線資料無效，請重新檢查。",unsupported_provider:"此模型廠家目前不受支援。",not_connected:"此模型廠家尚未連線。",invalid_credentials:"API 金鑰無效或已失效。",provider_unreachable:"暫時無法連線到模型廠家，請稍後再試。",provider_timeout:"模型廠家回應逾時，請稍後再試。",provider_rate_limited:"模型廠家目前限制請求，請稍後再試。",credential_store_unavailable:"安全憑證儲存服務暫時無法使用。",internal_error:"本機服務暫時無法完成操作，請稍後再試。",malformed_response:"本機服務回傳的資料無法安全使用，請重試。",network_error:"無法連線到本機服務，請確認 OpenSprite 正在執行。"} satisfies Record<ProviderErrorCode,string>)[code]; }
