"""Route registration for the web channel adapter."""

from __future__ import annotations

from typing import Any

from ..utils.log import logger


def register_web_routes(adapter: Any, *, ws_path: str, health_path: str) -> None:
    """Register HTTP and WebSocket routes on a prepared WebAdapter app."""
    app = adapter.app
    if app is None:
        raise RuntimeError("WebAdapter app must be created before registering routes")

    api = adapter._api
    router = app.router
    router.add_get(ws_path, adapter._handle_websocket)
    router.add_get(health_path, adapter._handle_health)
    router.add_get("/api/commands", api.handle_command_catalog)
    router.add_get("/api/curator/status", api.handle_curator_status)
    router.add_get("/api/curator/history", api.handle_curator_history)
    router.add_post("/api/curator/{action}", api.handle_curator_action)
    router.add_get("/api/sessions/status", api.handle_session_status)
    router.add_get("/api/sessions/timeline", api.handle_session_timeline)
    router.add_get("/api/sessions", api.handle_sessions)
    router.add_delete("/api/sessions", api.handle_sessions_delete)
    router.add_delete("/api/sessions/{session_id}", api.handle_sessions_delete)
    router.add_get("/api/storage/status", api.handle_storage_status)
    router.add_get("/api/background-processes", api.handle_background_processes)
    router.add_get("/api/evals/long-task", api.handle_long_task_eval_status)
    router.add_post("/api/evals/long-task/smoke", api.handle_long_task_eval_smoke)
    router.add_post("/api/evals/long-task/controlled", api.handle_long_task_eval_controlled)
    router.add_post("/api/evals/harness/controlled", api.handle_harness_controlled_eval)
    router.add_post("/api/evals/task-completion/smoke", api.handle_task_completion_eval_smoke)
    router.add_post("/api/evals/task-completion/run", api.handle_task_completion_eval_run)
    router.add_get("/api/evals/task-completion/history", api.handle_task_completion_eval_history)
    router.add_delete("/api/evals/task-completion/history", api.handle_task_completion_eval_history_clear)
    router.add_delete("/api/evals/task-completion/history/{eval_id}", api.handle_task_completion_eval_history_delete)
    router.add_get("/api/runs", api.handle_runs)
    router.add_get("/api/runs/{run_id}/summary", api.handle_run_summary)
    router.add_get("/api/runs/{run_id}", api.handle_run_trace)
    router.add_get("/api/runs/{run_id}/events", api.handle_run_events)
    router.add_post("/api/runs/{run_id}/cancel", api.handle_run_cancel)
    router.add_post("/api/runs/{run_id}/file-changes/{change_id}/revert", api.handle_run_file_change_revert)
    router.add_get("/api/permissions", api.handle_permissions)
    router.add_post("/api/permissions/{request_id}/approve", api.handle_permission_approve)
    router.add_post("/api/permissions/{request_id}/deny", api.handle_permission_deny)
    router.add_post("/api/worktrees/cleanup", api.handle_worktree_cleanup)
    router.add_get("/api/settings/channels", adapter._handle_settings_channels)
    router.add_post("/api/settings/channels", adapter._handle_settings_channel_create)
    router.add_put("/api/settings/channels/{channel_id}", adapter._handle_settings_channel_update)
    router.add_put("/api/settings/channels/{channel_id}/connect", adapter._handle_settings_channel_connect)
    router.add_post("/api/settings/channels/{channel_id}/disconnect", adapter._handle_settings_channel_disconnect)
    router.add_get("/api/settings/providers", adapter._handle_settings_providers)
    router.add_get("/api/settings/auth/openai-codex", adapter._handle_settings_codex_auth_status)
    router.add_post("/api/settings/auth/openai-codex/login", adapter._handle_settings_codex_auth_login)
    router.add_post("/api/settings/auth/openai-codex/poll", adapter._handle_settings_codex_auth_poll)
    router.add_post("/api/settings/auth/openai-codex/logout", adapter._handle_settings_codex_auth_logout)
    router.add_get("/api/settings/auth/copilot", adapter._handle_settings_copilot_auth_status)
    router.add_post("/api/settings/auth/copilot/login", adapter._handle_settings_copilot_auth_login)
    router.add_post("/api/settings/auth/copilot/poll", adapter._handle_settings_copilot_auth_poll)
    router.add_post("/api/settings/auth/copilot/logout", adapter._handle_settings_copilot_auth_logout)
    router.add_get("/api/settings/credentials", adapter._handle_settings_credentials)
    router.add_post("/api/settings/credentials", adapter._handle_settings_credential_create)
    router.add_delete("/api/settings/credentials/{provider}/{credential_id}", adapter._handle_settings_credential_delete)
    router.add_post("/api/settings/credentials/default", adapter._handle_settings_credential_default)
    router.add_put("/api/settings/providers/{provider_id}/connect", adapter._handle_settings_provider_connect)
    router.add_post("/api/settings/providers/{provider_id}/credential", adapter._handle_settings_provider_credential)
    router.add_post("/api/settings/providers/{provider_id}/disconnect", adapter._handle_settings_provider_disconnect)
    router.add_put("/api/settings/providers/{provider_id}/options", adapter._handle_settings_provider_options_update)
    router.add_get("/api/settings/models", adapter._handle_settings_models)
    router.add_post("/api/settings/models/select", adapter._handle_settings_model_select)
    router.add_get("/api/settings/llm", adapter._handle_settings_llm)
    router.add_put("/api/settings/llm", adapter._handle_settings_llm_update)
    router.add_get("/api/settings/update", adapter._handle_settings_update_status)
    router.add_post("/api/settings/update", adapter._handle_settings_update_apply)
    router.add_get("/api/settings/media", adapter._handle_settings_media)
    router.add_put("/api/settings/media", adapter._handle_settings_media_update)
    router.add_get("/api/settings/schedule", adapter._handle_settings_schedule)
    router.add_put("/api/settings/schedule", adapter._handle_settings_schedule_update)
    router.add_get("/api/settings/network", adapter._handle_settings_network)
    router.add_put("/api/settings/network", adapter._handle_settings_network_update)
    router.add_get("/api/settings/permissions", adapter._handle_settings_permissions)
    router.add_put("/api/settings/permissions", adapter._handle_settings_permissions_update)
    router.add_get("/api/settings/harness-policy-preview", adapter._handle_settings_harness_policy_preview)
    router.add_get("/api/settings/search", adapter._handle_settings_search)
    router.add_get("/api/settings/search/searxng-options", adapter._handle_settings_search_searxng_options)
    router.add_put("/api/settings/search", adapter._handle_settings_search_update)
    router.add_get("/api/settings/browser", adapter._handle_settings_browser)
    router.add_put("/api/settings/browser", adapter._handle_settings_browser_update)
    router.add_post("/api/settings/browser/test", adapter._handle_settings_browser_test)
    router.add_post("/api/settings/browser/doctor", adapter._handle_settings_browser_doctor)
    router.add_post("/api/settings/browser/install", adapter._handle_settings_browser_install)
    router.add_get("/api/settings/log", adapter._handle_settings_log)
    router.add_put("/api/settings/log", adapter._handle_settings_log_update)
    router.add_get("/api/settings/mcp", adapter._handle_settings_mcp)
    router.add_post("/api/settings/mcp", adapter._handle_settings_mcp_create)
    router.add_post("/api/settings/mcp/reload", adapter._handle_settings_mcp_reload)
    router.add_put("/api/settings/mcp/{server_id}", adapter._handle_settings_mcp_update)
    router.add_delete("/api/settings/mcp/{server_id}", adapter._handle_settings_mcp_delete)
    router.add_get("/api/cron/jobs", adapter._handle_cron_jobs)
    router.add_post("/api/cron/jobs", adapter._handle_cron_job_create)
    router.add_put("/api/cron/jobs/{job_id}", adapter._handle_cron_job_update)
    router.add_delete("/api/cron/jobs/{job_id}", adapter._handle_cron_job_delete)
    router.add_post("/api/cron/jobs/{job_id}/{action}", adapter._handle_cron_job_action)
    router.add_get("/", adapter._handle_frontend_index)
    router.add_get("/index.html", adapter._handle_frontend_index)
    if adapter._frontend_dir is not None:
        router.add_get(r"/{asset_path:.+\..+}", adapter._handle_frontend_asset)
    else:
        logger.info("Web adapter did not find a frontend directory; serving API endpoints only")
