"""Shared runtime tool name constants."""

from __future__ import annotations


BATCH_TOOL_NAME = "batch"
READ_FILE_TOOL_NAME = "read_file"
LIST_DIR_TOOL_NAME = "list_dir"
GLOB_FILES_TOOL_NAME = "glob_files"
GREP_FILES_TOOL_NAME = "grep_files"
CODE_NAVIGATION_TOOL_NAME = "code_navigation"
APPLY_PATCH_TOOL_NAME = "apply_patch"
WRITE_FILE_TOOL_NAME = "write_file"
EDIT_FILE_TOOL_NAME = "edit_file"
EXEC_TOOL_NAME = "exec"
PROCESS_TOOL_NAME = "process"
READ_SKILL_TOOL_NAME = "read_skill"
CONFIGURE_SKILL_TOOL_NAME = "configure_skill"
LIST_RUN_FILE_CHANGES_TOOL_NAME = "list_run_file_changes"
PREVIEW_RUN_FILE_CHANGE_REVERT_TOOL_NAME = "preview_run_file_change_revert"
ANALYZE_IMAGE_TOOL_NAME = "analyze_image"
OCR_IMAGE_TOOL_NAME = "ocr_image"
TRANSCRIBE_AUDIO_TOOL_NAME = "transcribe_audio"
ANALYZE_VIDEO_TOOL_NAME = "analyze_video"
SEND_MEDIA_TOOL_NAME = "send_media"
WORKSPACE_DISCOVERY_TOOL_NAMES = frozenset(
    {
        READ_FILE_TOOL_NAME,
        LIST_DIR_TOOL_NAME,
        GLOB_FILES_TOOL_NAME,
        GREP_FILES_TOOL_NAME,
        CODE_NAVIGATION_TOOL_NAME,
    }
)
WORKSPACE_WRITE_TOOL_NAMES = frozenset(
    {
        APPLY_PATCH_TOOL_NAME,
        WRITE_FILE_TOOL_NAME,
        EDIT_FILE_TOOL_NAME,
    }
)
EXECUTION_TOOL_NAMES = frozenset({EXEC_TOOL_NAME, PROCESS_TOOL_NAME})
RUN_TRACE_READ_TOOL_NAMES = frozenset(
    {
        LIST_RUN_FILE_CHANGES_TOOL_NAME,
        PREVIEW_RUN_FILE_CHANGE_REVERT_TOOL_NAME,
    }
)
SKILL_REVIEW_TOOL_NAMES = frozenset({READ_SKILL_TOOL_NAME, CONFIGURE_SKILL_TOOL_NAME})
MEDIA_ANALYSIS_TOOL_NAMES = frozenset(
    {
        ANALYZE_IMAGE_TOOL_NAME,
        OCR_IMAGE_TOOL_NAME,
        TRANSCRIBE_AUDIO_TOOL_NAME,
        ANALYZE_VIDEO_TOOL_NAME,
    }
)
MEDIA_TOOL_NAMES = frozenset({*MEDIA_ANALYSIS_TOOL_NAMES, SEND_MEDIA_TOOL_NAME})
